#!/bin/bash
#
#Copyright (c) 2023 Qualcomm Innovation Center, Inc. All rights reserved.
#SPDX-License-Identifier: BSD-3-Clause-Clear
#

IMAGE_NAME="qcom-robotics-console-image"
QIRF_NAME="qirf-sdk"

# API check is enabled by default
APICHECK_ENABLED=0

ERROR(){
    local message="$1"
    echo -e "\e[91mError: $message\e[0m"
}

USAGE() {
    echo
    echo "Usage: $0 [image name] [--noapicheck] [-h]"
    echo "    --noapicheck             Disable API check"
    echo "    -h or --help             Display help message"
    echo
    exit 1
}

start_apicheck() {
    echo "Unpacking QIRF SDK..."
    if ! ls $(pwd)/tmp-glibc/deploy/artifacts/$QIRF_NAME*.tar.gz &> /dev/null; then
        echo "    There are no QIRF SDK in $(pwd)/tmp-glibc/deploy/artifacts/"
        exit 1
    else
        cd $(pwd)/tmp-glibc/deploy/artifacts
        tar -zvxf $QIRF_NAME*.tar.gz && cd ./$QIRF_NAME || exit 1
    fi

    echo "Extracting Toolchain..."
    ./setup.sh || exit 1

    echo "Compile Samples, and check APIs..."
    list=()
    for package_xml in $(find ./sample-code -name "package.xml"); do
        package_dir=$(dirname $package_xml)
        list+=("$package_dir")
    done

    for dir in "${list[@]}"; do
        cd $dir || exit 1
        colcon build
        if [ $? -ne 0 ]; then
            echo "Error building in $dir. Exiting."
            exit 1
        fi
        colcon test --event-handler=console_direct+
        if [ $? -ne 0 ]; then
            echo "Error testing in $dir. Exiting."
            exit 1
        fi
        cd ..
    done
}

check_dependencies() {
    echo "Checking HOST Dependencies..."

    if ! dpkg -l | grep ros-humble-desktop &> /dev/null; then
        echo "    ros-foxy-desktop is not installed. Please install"
        exit 1
    else
        echo "    ros-humble-desktop is installed"
    fi

    if ! dpkg -l | grep python3-colcon-common-extensions &> /dev/null; then
        echo "    python3-colcon-common-extensions is not installed. Please install"
        exit 1
    else
        echo "    python3-colcon-common-extensions is installed"
    fi

    if ! dpkg -l | grep libgtest-dev &> /dev/null; then
        echo "    libgtest-dev is not installed. Please install"
        exit 1
    else
        echo "    libgtest-dev is installed"
    fi
}

compile_qirf(){
    # Generate QIRF SDK...
    echo "Generating QIRF SDK to provide toolchain with:"
    echo "    bitbake $QIRF_NAME"
    echo
    bitbake $QIRF_NAME

    # Start APIs Check
    if [ $APICHECK_ENABLED -eq 1 ]; then
        echo "Starting API Check..."
        check_dependencies
        start_apicheck
    else
        echo "Skip API Check..."
    fi
}

# Parse arguments...
if [ $# -gt 0 ]; then
    case "$1" in
        "-h")
            USAGE
            ;;
        "--help")
            USAGE
            ;;
        *)
            IMAGE_NAME=$1
            ;;
    esac

    if [ $# -eq 2 ]; then
        case "$2" in
            "--noapicheck")
                APICHECK_ENABLED=0
                ;;
        esac
    fi
else
    USAGE
fi

# Start compile...
compile_qirf
echo "Compile Successfully!"

